"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { MAP_ARCHETYPES, POWER_UP_KINDS, POWER_UP_META, SNAKES } from "@/game/constants";
import type { PowerUpBehaviorStats, PowerUpKind, RewardBreakdown } from "@/game/types";

type Sample = { id: string; seed_index: number; environment_steps: number; policy_version: number; sample_kind: string; metrics: any; created_at: string };
type ReleaseSummary = { id: string; status: string; coverage: "full" | "partial" | "unavailable"; eligible: boolean | null; selectedSeedIndex: number | null; seedPassCount: number | null; seedCount: number | null; baselineReleaseId: string | null; aggregate: Record<string, any> | null; createdAt: string };
type Overview = { coverage: "full" | "partial" | "unavailable"; activeExperiment: any | null; latestSample: Sample | null; production: ReleaseSummary | null; latestCandidate: ReleaseSummary | null; releases: ReleaseSummary[] };
type ReleaseDetail = { summary: ReleaseSummary; coverage: string; selectedResult: any | null; seedResults: any[]; gates: Record<string, boolean> };
type Comparison = { candidate: ReleaseDetail; baseline: ReleaseDetail; statisticalComparisonAvailable: boolean; metrics: Array<{ key: string; candidate: number; baseline: number; delta: number; direction: "higher" | "lower"; improved: boolean }>; pairedWinInterval: [number, number] | null; gates: Record<string, boolean> };

const api = process.env.NEXT_PUBLIC_SERVER_TRAINING_API ?? "/server-api";
const metricNames: Record<string, string> = { winRate: "Win rate", avgScore: "Average score", foodPerMatch: "Food / match", avgSurvivalTicks: "Survival ticks", powerUpClaimRate: "Powerup claim rate", approachWithoutClaimRate: "Approach without claim", deathsPerThousandTicks: "Deaths / 1,000 ticks", scriptedWinRate: "Scripted win rate", rareFoodPerMatch: "Rare food / match", objectiveCapturesPerMatch: "Core captures / match", bountyKillsPerMatch: "Bounty kills / match", hazardDeathsPerMatch: "Hazard deaths / match", zoneDeathsPerMatch: "Zone deaths / match" };
const rewardNames: Record<string, string> = { step: "Step", survival: "Survival", foodApproach: "Food approach", foodClaim: "Food claim", powerUpApproach: "Powerup approach", powerUpClaim: "Powerup claim", zonePositioning: "Zone positioning", objectiveApproach: "Core approach", objectiveCapture: "Core capture", bountyKill: "Bounty kill", rareFoodClaim: "Rare food", kill: "Kill", death: "Death", win: "Win" };
const scenarios = ["survival", "powerup", "safezone", "hazard", "objective", "battle", "series"] as const;

function percent(value: unknown): string { return typeof value === "number" && Number.isFinite(value) ? `${(value * 100).toFixed(1)}%` : "N/A"; }
function number(value: unknown, digits = 1): string { return typeof value === "number" && Number.isFinite(value) ? value.toFixed(digits) : "N/A"; }
function metricValue(key: string, value: number): string { return key.toLowerCase().includes("rate") || key === "winRate" ? percent(value) : number(value); }

function LineChart({ title, samples, lines }: { title: string; samples: Sample[]; lines: Array<{ label: string; color: string; value: (sample: Sample) => number | null }> }) {
  const points = lines.map((line) => ({ ...line, values: samples.map((sample, index) => ({ x: index, y: line.value(sample) })).filter((point): point is { x: number; y: number } => typeof point.y === "number" && Number.isFinite(point.y)) }));
  const all = points.flatMap((line) => line.values.map((entry) => entry.y));
  if (!samples.length || !all.length) return <div className="intel-empty">No telemetry collected for this chart yet.</div>;
  const min = Math.min(...all); const max = Math.max(...all); const range = Math.max(max - min, .0001); const width = 600; const height = 170;
  return <figure className="intel-chart"><figcaption>{title}</figcaption><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`${title}. ${samples.length} telemetry samples.`}>
    <line x1="0" y1={height - 1} x2={width} y2={height - 1} className="chart-axis" />
    {points.map((line) => <polyline key={line.label} fill="none" stroke={line.color} strokeWidth="2.5" points={line.values.map((entry) => `${entry.x / Math.max(samples.length - 1, 1) * width},${height - (entry.y - min) / range * (height - 12) - 6}`).join(" ")} />)}
  </svg><div className="chart-legend">{points.map((line) => <span key={line.label}><i style={{ background: line.color }} />{line.label}</span>)}</div></figure>;
}

function aggregatePowerUps(detail: ReleaseDetail | null): Record<PowerUpKind, PowerUpBehaviorStats> | null {
  const rows = detail?.selectedResult?.perSnake?.map((row: any) => row.candidate).filter(Boolean) ?? [];
  if (!rows.length || !rows.some((row: any) => row.powerUpBehavior)) return null;
  return Object.fromEntries(POWER_UP_KINDS.map((kind) => {
    const values = rows.map((row: any) => row.powerUpBehavior?.[kind]).filter(Boolean);
    const sum = (key: keyof PowerUpBehaviorStats) => values.reduce((total: number, value: any) => total + (typeof value[key] === "number" ? value[key] : 0), 0);
    const seen = sum("seen"); const claimed = sum("claimed");
    const weighted = (key: "avgInitialDistance" | "avgClosestDistance" | "avgClaimTicks", count: "seen" | "claimed") => { const total = values.reduce((result: number, value: any) => result + (value[key] ?? 0) * value[count], 0); const divisor = sum(count); return divisor ? total / divisor : null; };
    return [kind, { seen, reachable: sum("reachable"), pursued: sum("pursued"), claimed, ignored: sum("ignored"), pursuitWithoutClaim: sum("pursuitWithoutClaim"), pursuitDeaths: sum("pursuitDeaths"), avgInitialDistance: weighted("avgInitialDistance", "seen"), avgClosestDistance: weighted("avgClosestDistance", "seen"), avgClaimTicks: weighted("avgClaimTicks", "claimed") }];
  })) as Record<PowerUpKind, PowerUpBehaviorStats>;
}

export function IntelligenceDashboard() {
  const [authenticated, setAuthenticated] = useState<boolean | null>(null); const [password, setPassword] = useState("");
  const [overview, setOverview] = useState<Overview | null>(null); const [samples, setSamples] = useState<Sample[]>([]);
  const [candidateId, setCandidateId] = useState(""); const [baselineId, setBaselineId] = useState("");
  const [detail, setDetail] = useState<ReleaseDetail | null>(null); const [comparison, setComparison] = useState<Comparison | null>(null);
  const [error, setError] = useState(""); const [loading, setLoading] = useState(false);

  const request = useCallback(async <T,>(path: string, init: RequestInit = {}): Promise<T> => { const response = await fetch(`${api}${path}`, { ...init, credentials: "same-origin", headers: { "Content-Type": "application/json", ...init.headers } }); if (!response.ok) { const payload = await response.json().catch(() => ({})); throw new Error(payload.detail ?? `Request failed (${response.status}).`); } return response.json() as Promise<T>; }, []);
  const refresh = useCallback(async () => { try { const next = await request<Overview>("/intelligence/overview"); setOverview(next); setAuthenticated(true); setError(""); if (!candidateId) setCandidateId(next.latestCandidate?.id ?? next.production?.id ?? next.releases[0]?.id ?? ""); if (!baselineId) setBaselineId(next.production?.id && next.production.id !== next.latestCandidate?.id ? next.production.id : next.releases.find((release) => release.id !== (next.latestCandidate?.id ?? next.production?.id))?.id ?? ""); } catch (reason) { if (reason instanceof Error && reason.message.includes("login")) setAuthenticated(false); else setError(reason instanceof Error ? reason.message : "Intelligence server is unavailable."); } }, [baselineId, candidateId, request]);

  useEffect(() => { void request("/auth/me").then(() => setAuthenticated(true)).catch(() => setAuthenticated(false)); }, [request]);
  useEffect(() => { const requested = new URLSearchParams(window.location.search).get("release"); if (requested) setCandidateId(requested); }, []);
  useEffect(() => { if (!authenticated) return; void refresh(); const timer = window.setInterval(() => void refresh(), 2_000); return () => window.clearInterval(timer); }, [authenticated, refresh]);
  useEffect(() => { if (!authenticated || !overview?.activeExperiment?.id) { setSamples([]); return; } const load = () => request<Sample[]>(`/intelligence/experiments/${overview.activeExperiment.id}/series`).then(setSamples).catch((reason) => setError(reason.message)); void load(); const timer = window.setInterval(load, 10_000); return () => window.clearInterval(timer); }, [authenticated, overview?.activeExperiment?.id, request]);
  useEffect(() => { if (!candidateId) { setDetail(null); setComparison(null); return; } setLoading(true); const task = baselineId && baselineId !== candidateId ? request<Comparison>(`/intelligence/compare?candidate=${encodeURIComponent(candidateId)}&baseline=${encodeURIComponent(baselineId)}`).then((value) => { setComparison(value); setDetail(value.candidate); }) : request<ReleaseDetail>(`/intelligence/releases/${candidateId}`).then((value) => { setDetail(value); setComparison(null); }); void task.catch((reason) => setError(reason.message)).finally(() => setLoading(false)); }, [baselineId, candidateId, request]);

  const login = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); try { await request("/auth/login", { method: "POST", body: JSON.stringify({ password }) }); setPassword(""); setAuthenticated(true); } catch (reason) { setError(reason instanceof Error ? reason.message : "Login failed."); } finally { setLoading(false); } };
  const powerUps = useMemo(() => aggregatePowerUps(detail), [detail]);
  const selectedRows = detail?.selectedResult?.perSnake ?? [];
  const snakeEntries = useMemo(() => {
    const ids = new Set<string>(SNAKES.map((snake) => snake.id));
    samples.forEach((sample) => Object.keys(sample.metrics?.bySnake ?? {}).forEach((id) => ids.add(id)));
    selectedRows.forEach((row: any) => { if (row.snakeId) ids.add(row.snakeId); });
    const palette = ["#68f7c1", "#ff6b7a", "#ffd166", "#9d83ff", "#62e6ff", "#ff9f6e", "#c49bff", "#7dff8a"];
    return [...ids].map((id, index) => SNAKES.find((snake) => snake.id === id) ?? { id, name: id, color: palette[index % palette.length], accent: "#ffffff" });
  }, [samples, selectedRows]);
  const rewards = detail?.summary.aggregate?.rewardBreakdown as RewardBreakdown | undefined;
  const deathCauses = selectedRows.reduce((totals: Record<string, number>, row: any) => { for (const [key, value] of Object.entries(row.candidate?.deathCauses ?? {})) totals[key] = (totals[key] ?? 0) + Number(value); return totals; }, {});
  const maxDeathCause = Math.max(1, ...(Object.values(deathCauses) as number[]));
  const adaptive = selectedRows.reduce((totals: Record<string, number>, row: any) => {
    const behavior = row.candidate?.adaptive ?? {};
    for (const key of ["rareFoodClaims", "objectiveCaptures", "bountyKills", "hazardDeaths", "zoneDeaths", "zoneWarnings", "zoneRepositions", "hazardEncounters", "hazardEvasions", "objectiveOpportunities", "objectivePursuits", "objectivePursuitDeaths", "crownClaims"]) totals[key] = (totals[key] ?? 0) + Number(behavior[key] ?? row.candidate?.[key] ?? 0);
    for (const phase of ["opening", "midgame", "endgame"]) totals[`phase:${phase}`] = (totals[`phase:${phase}`] ?? 0) + Number(row.candidate?.phaseSurvival?.[phase] ?? 0);
    return totals;
  }, {});
  const evaluated = detail?.selectedResult ?? {};
  const adaptiveEvaluation = evaluated.adaptive as Record<string, number> | undefined;
  const phaseWinRates = evaluated.phaseWinRates as Record<string, { candidate: number; baseline: number; candidateMatches: number }> | undefined;
  const mapWinRates = evaluated.mapWinRates as Record<string, { candidate: number; baseline: number; candidateMatches: number }> | undefined;
  const trainingMapWinRates = evaluated.trainingMapWinRates as Record<string, { candidate: number; baseline: number; candidateMatches: number }> | undefined;
  const counterResults = evaluated.powerUpCounters as Record<PowerUpKind, { candidate: number; candidateOpportunities: number; candidateRate: number; baseline: number; baselineOpportunities: number; baselineRate: number }> | undefined;
  const heldOutVsTraining = evaluated.heldOutVsTraining as { candidate: { heldOut: number; training: number }; baseline: { heldOut: number; training: number } } | undefined;

  if (authenticated === null) return <main className="page-shell status-screen"><h1>Loading intelligence…</h1></main>;
  if (!authenticated) return <main className="page-shell intelligence-page"><section className="server-login glass-card"><span className="eyebrow">Private local analytics</span><h1>AI INTELLIGENCE</h1><p>Use the same administrator password as Server Lab.</p><form onSubmit={login}><label>Administrator password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} minLength={12} required /></label><button className="primary-button" disabled={loading}>Open intelligence</button></form>{error && <div className="system-banner" role="alert">{error}</div>}</section></main>;

  return <main className="page-shell intelligence-page">
    <section className="hero-row"><div><span className="eyebrow">Evidence over intuition</span><h1>AI<br /><em>INTELLIGENCE.</em></h1></div><p>See what every release learned, why it passed or failed, and whether powerup behavior improved without sacrificing survival.</p></section>
    {error && <div className="system-banner" role="alert">{error}</div>}
    <section className="intel-summary-grid">
      <article className="glass-card intel-summary"><span>Active training</span><strong>{overview?.activeExperiment?.status?.toUpperCase() ?? "IDLE"}</strong><small>{overview?.latestSample ? `${overview.latestSample.environment_steps.toLocaleString()} steps · ${number(overview.latestSample.metrics.throughputStepsPerSecond, 0)} steps/s` : "No instrumented samples"}</small></article>
      <article className="glass-card intel-summary"><span>Production</span><strong>{overview?.production?.id.slice(0, 8) ?? "NONE"}</strong><small>{overview?.production?.aggregate ? `${percent(overview.production.aggregate.winRate)} win rate` : "No production analytics"}</small></article>
      <article className="glass-card intel-summary"><span>Latest candidate</span><strong>{overview?.latestCandidate?.id.slice(0, 8) ?? "NONE"}</strong><small>{overview?.latestCandidate ? `${overview.latestCandidate.seedPassCount ?? "?"}/${overview.latestCandidate.seedCount ?? "?"} seeds passed` : "Train a model to begin"}</small></article>
      <article className="glass-card intel-summary"><span>Data coverage</span><strong>{overview?.coverage.toUpperCase() ?? "UNAVAILABLE"}</strong><small>Missing history is always shown as N/A.</small></article>
    </section>

    <section className="glass-card intel-panel"><div className="panel-heading"><div><span className="eyebrow">Live learning</span><h2>Training curves</h2></div></div>
      <div className="intel-chart-grid">
        <LineChart title="Loss by snake" samples={samples} lines={snakeEntries.map((snake) => ({ label: snake.name, color: snake.color, value: (sample) => sample.metrics.bySnake?.[snake.id]?.loss ?? null }))} />
        <LineChart title="Exploration by snake" samples={samples} lines={snakeEntries.map((snake) => ({ label: snake.name, color: snake.color, value: (sample) => sample.metrics.bySnake?.[snake.id]?.epsilon ?? null }))} />
        <LineChart title="Powerup claim rate and throughput" samples={samples} lines={[{ label: "Claim rate", color: "#68f7c1", value: (sample) => sample.metrics.claimRate ?? null }, { label: "Throughput / 10k", color: "#e9c46a", value: (sample) => typeof sample.metrics.throughputStepsPerSecond === "number" ? sample.metrics.throughputStepsPerSecond / 10_000 : null }]} />
        <LineChart title="Cumulative reward by snake" samples={samples} lines={snakeEntries.map((snake) => ({ label: snake.name, color: snake.color, value: (sample) => sample.metrics.bySnake?.[snake.id]?.rewardTotal ?? null }))} />
        <LineChart title="Scenario exposure" samples={samples} lines={scenarios.map((scenario, index) => ({ label: scenario, color: ["#68f7c1", "#62e6ff", "#81a7ff", "#ff4967", "#ffd45b", "#ff9f6e", "#c49bff"][index], value: (sample) => snakeEntries.reduce((sum, snake) => sum + Number(sample.metrics.bySnake?.[snake.id]?.scenarioSteps?.[scenario] ?? 0), 0) }))} />
        <LineChart title="Adaptive reward components" samples={samples} lines={[{ label: "Zone", color: "#81a7ff", value: (sample) => snakeEntries.reduce((sum, snake) => sum + Number(sample.metrics.bySnake?.[snake.id]?.reward?.zone_positioning ?? 0), 0) }, { label: "Core", color: "#62e6ff", value: (sample) => snakeEntries.reduce((sum, snake) => sum + Number(sample.metrics.bySnake?.[snake.id]?.reward?.objective_capture ?? 0), 0) }, { label: "Bounty", color: "#ffd45b", value: (sample) => snakeEntries.reduce((sum, snake) => sum + Number(sample.metrics.bySnake?.[snake.id]?.reward?.bounty_kill ?? 0), 0) }, { label: "Rare food", color: "#ff9f6e", value: (sample) => snakeEntries.reduce((sum, snake) => sum + Number(sample.metrics.bySnake?.[snake.id]?.reward?.rare_food_claim ?? 0), 0) }]} />
      </div>
      {overview?.latestSample && <div className="intel-live-grid">{snakeEntries.map((snake) => { const row = overview.latestSample!.metrics.bySnake?.[snake.id]; return <div key={snake.id}><b>{snake.name}</b><span>ε {number(row?.epsilon, 3)}</span>{scenarios.map((scenario) => <span key={scenario}>{Number(row?.scenarioSteps?.[scenario] ?? 0).toLocaleString()} {scenario}</span>)}</div>; })}</div>}
    </section>

    <section className="glass-card intel-panel"><div className="panel-heading"><div><span className="eyebrow">Release laboratory</span><h2>Compare trained brains</h2></div><span className={`coverage-pill ${detail?.coverage ?? "unavailable"}`}>{detail?.coverage ?? "unavailable"}</span></div>
      <div className="intel-selectors"><label>Candidate<select value={candidateId} onChange={(event) => setCandidateId(event.target.value)}><option value="">Select release</option>{overview?.releases.map((release) => <option key={release.id} value={release.id}>{release.id.slice(0, 8)} · {release.status}</option>)}</select></label><label>Baseline<select value={baselineId} onChange={(event) => setBaselineId(event.target.value)}><option value="">No baseline</option>{overview?.releases.filter((release) => release.id !== candidateId).map((release) => <option key={release.id} value={release.id}>{release.id.slice(0, 8)} · {release.status}</option>)}</select></label></div>
      {loading ? <p>Loading comparison…</p> : comparison?.metrics.length ? <div className="intel-metric-table">{comparison.metrics.map((metric) => <div key={metric.key}><strong>{metricNames[metric.key] ?? metric.key}</strong><span>{metricValue(metric.key, metric.baseline)}</span><span>{metricValue(metric.key, metric.candidate)}</span><b className={metric.improved ? "metric-good" : "metric-bad"}>{metric.delta > 0 ? "+" : ""}{metricValue(metric.key, metric.delta)}</b></div>)}</div> : <div className="intel-empty">Choose compatible releases with recorded analytics to compare them.</div>}
      <div className="intel-gates"><h3>Benchmark gates</h3>{comparison && !comparison.statisticalComparisonAvailable && <p>This pair was not benchmarked head-to-head; descriptive deltas are shown without statistical claims.</p>}{Object.entries(comparison?.gates ?? detail?.gates ?? {}).map(([gate, passed]) => <span className={passed ? "gate-pass" : "gate-fail"} key={gate}>{passed ? "PASS" : "FAIL"} · {gate.replace(/([A-Z])/g, " $1")}</span>)}{comparison?.pairedWinInterval && <span>95% paired interval: {number(comparison.pairedWinInterval[0], 3)} to {number(comparison.pairedWinInterval[1], 3)}</span>}</div>
    </section>

    <section className="intel-two-column"><article className="glass-card intel-panel"><span className="eyebrow">Individual policies</span><h2>Per-snake intelligence</h2><div className="intel-snake-grid">{selectedRows.length ? selectedRows.map((row: any) => <div key={row.snakeId}><strong>{row.snakeId.toUpperCase()}</strong><span>{percent(row.candidate?.wins / Math.max(1, detail?.selectedResult?.matches ?? 1))} wins</span><span>{percent(row.candidate?.powerUpClaimRate)} claims</span><span>{number(row.candidate?.avgSurvivalTicks)} survival</span><span>{number(row.candidate?.deathsPerThousandTicks)} deaths / 1k</span></div>) : <div className="intel-empty">Per-snake analytics unavailable.</div>}</div></article>
      <article className="glass-card intel-panel"><span className="eyebrow">Failure analysis</span><h2>Death causes</h2>{Object.keys(deathCauses).length ? <div className="intel-bars">{(Object.entries(deathCauses) as Array<[string, number]>).map(([key, value]) => <div key={key}><span>{key}</span><i style={{ width: `${Math.min(100, value / maxDeathCause * 100)}%` }} /><b>{value}</b></div>)}</div> : <div className="intel-empty">Death-cause telemetry unavailable.</div>}</article></section>

    <section className="glass-card intel-panel"><span className="eyebrow">Powerup behavior</span><h2>Seen, pursued, claimed, or intelligently ignored</h2>{powerUps ? <div className="powerup-matrix"><div className="matrix-head"><span>Kind</span><span>Seen</span><span>Reachable</span><span>Pursued</span><span>Claimed</span><span>Ignored</span><span>Missed</span><span>Pursuit deaths</span></div>{POWER_UP_KINDS.map((kind) => { const row = powerUps[kind]; return <div key={kind}><strong style={{ color: POWER_UP_META[kind].color }}>{POWER_UP_META[kind].icon} {POWER_UP_META[kind].name}</strong><span>{row.seen}</span><span>{row.reachable}</span><span>{row.pursued}</span><span>{row.claimed}</span><span>{row.ignored}</span><span>{row.pursuitWithoutClaim}</span><span>{row.pursuitDeaths}</span></div>; })}</div> : <div className="intel-empty">Per-powerup intelligence begins with metrics schema v2.</div>}
      <h3 className="intel-subheading">Successful contextual counter use</h3>{counterResults ? <div className="powerup-matrix counter-matrix"><div className="matrix-head"><span>Powerup</span><span>Candidate</span><span>Opportunities</span><span>Success rate</span><span>Baseline rate</span><span>Change</span></div>{POWER_UP_KINDS.map((kind) => { const row = counterResults[kind]; const delta = row.candidateRate - row.baselineRate; return <div key={kind}><strong style={{ color: POWER_UP_META[kind].color }}>{POWER_UP_META[kind].icon} {POWER_UP_META[kind].name}</strong><span>{row.candidate}</span><span>{row.candidateOpportunities}</span><span>{percent(row.candidateRate)}</span><span>{row.baselineOpportunities ? percent(row.baselineRate) : "N/A"}</span><span className={delta >= 0 ? "metric-good" : "metric-bad"}>{row.baselineOpportunities ? `${delta >= 0 ? "+" : ""}${percent(delta)}` : "N/A"}</span></div>; })}</div> : <div className="intel-empty">Counter-use evidence begins with metrics schema v3.</div>}</section>

    <section className="glass-card intel-panel"><span className="eyebrow">Adaptive Arena</span><h2>Zone, hazard, objective, bounty, and series intelligence</h2>{selectedRows.length ? <><div className="reward-grid"><div><span>Zone reposition rate</span><strong>{adaptiveEvaluation ? percent(adaptiveEvaluation.zoneRepositionRateCandidate) : percent((adaptive.zoneRepositions ?? 0) / Math.max(1, adaptive.zoneWarnings ?? 0))}</strong></div><div><span>Hazard evasion rate</span><strong>{adaptiveEvaluation ? percent(adaptiveEvaluation.hazardAvoidanceRateCandidate) : percent((adaptive.hazardEvasions ?? 0) / Math.max(1, adaptive.hazardEncounters ?? 0))}</strong></div><div><span>Hazard-blind reference</span><strong>{adaptiveEvaluation ? percent(adaptiveEvaluation.hazardAvoidanceRateBlind) : "N/A"}</strong></div><div><span>Core capture rate</span><strong>{adaptiveEvaluation ? percent(adaptiveEvaluation.objectiveCaptureRateCandidate) : percent((adaptive.objectiveCaptures ?? 0) / Math.max(1, adaptive.objectiveOpportunities ?? 0))}</strong></div><div><span>Core-pursuit death rate</span><strong>{adaptiveEvaluation ? percent(adaptiveEvaluation.objectivePursuitDeathRateCandidate) : percent((adaptive.objectivePursuitDeaths ?? 0) / Math.max(1, adaptive.objectiveOpportunities ?? 0))}</strong></div><div><span>Counter success rate</span><strong>{adaptiveEvaluation ? percent(adaptiveEvaluation.counterSuccessRateCandidate) : "N/A"}</strong></div><div><span>Round 1 win rate</span><strong>{adaptiveEvaluation ? percent(adaptiveEvaluation.roundOneWinRate) : "N/A"}</strong></div><div><span>Round 3 win rate</span><strong>{adaptiveEvaluation ? percent(adaptiveEvaluation.roundThreeWinRate) : "N/A"}</strong></div><div><span>Simulation throughput</span><strong>{adaptiveEvaluation ? `${number(adaptiveEvaluation.candidateThroughput, 0)} /s` : "N/A"}</strong></div><div><span>Rare food claims</span><strong>{adaptive.rareFoodClaims ?? 0}</strong></div><div><span>Bounty kills</span><strong>{adaptive.bountyKills ?? 0}</strong></div><div><span>Crown claims</span><strong>{adaptive.crownClaims ?? 0}</strong></div></div>
      <div className="intel-comparison-grid"><div><h3>Win rate by phase</h3><div className="intel-bars">{["opening", "midgame", "endgame"].map((phase) => { const row = phaseWinRates?.[phase]; return <div key={phase}><span>{phase}</span><i style={{ width: `${(row?.candidate ?? 0) * 100}%` }} /><b>{row?.candidateMatches ? percent(row.candidate) : "N/A"}</b></div>; })}</div></div><div><h3>Generalization</h3><div className="reward-grid compact-reward-grid"><div><span>Candidate held-out</span><strong>{heldOutVsTraining ? percent(heldOutVsTraining.candidate.heldOut) : "N/A"}</strong></div><div><span>Candidate training maps</span><strong>{heldOutVsTraining ? percent(heldOutVsTraining.candidate.training) : "N/A"}</strong></div><div><span>Baseline held-out</span><strong>{heldOutVsTraining ? percent(heldOutVsTraining.baseline.heldOut) : "N/A"}</strong></div></div></div></div>
      <h3 className="intel-subheading">Held-out map performance</h3><div className="intel-bars adaptive-map-bars">{MAP_ARCHETYPES.map((map) => { const row = mapWinRates?.[map]; const training = trainingMapWinRates?.[map]; return <div key={map}><span>{map.replace(/-/g, " ")}</span><i style={{ width: `${(row?.candidate ?? 0) * 100}%` }} /><b>{row?.candidateMatches ? `${percent(row.candidate)} / train ${percent(training?.candidate)}` : "N/A"}</b></div>; })}</div></> : <div className="intel-empty">Adaptive Arena metrics begin with schema v3 releases.</div>}</section>

    <section className="glass-card intel-panel"><span className="eyebrow">Reward diagnostics</span><h2>What motivates this policy</h2>{rewards ? <div className="reward-grid">{Object.entries(rewards).map(([key, value]) => <div key={key}><span>{rewardNames[key] ?? key}</span><strong className={Number(value) >= 0 ? "metric-good" : "metric-bad"}>{number(value, 0)}</strong></div>)}</div> : <div className="intel-empty">Reward-component analytics unavailable.</div>}</section>
  </main>;
}
